### ISSUE TITLE
Maimclip: Maim can write directly to stdout now.

### ISSUE THREAD

**Issue by naelstrof** [orschiro/scriptlets#1]
Well it kind of can now. Check https://github.com/naelstrof/maim/commit/b9c44d8e4799e3c55ffb236300683c98fec8382a, it lets you do something like this:

``` bash
maim -f png /dev/stdout | xclip -selection c
```

It'll keep maimclip from needing to write to the disk, even if it is the ramdisk.

Great stuff though, really small and elegant. Keep up the good work!

**Comment by orschiro** [comment]
@naelstrof 

Thanks for your comment! Your suggestion would make the use of copyq obsolete, correct?

Warmly,

Robert

**Comment by naelstrof** [comment]
No idea. It's more about efficiency than functionality. You're writing to the ramdisk which could be avoided with something like `maim -f png /dev/stdout | copyq write image/png -`
But I don't use copyq so I'm not sure.

**Comment by orschiro** [comment]
@naelstrof 

Thanks! Very smart idea!

https://github.com/orschiro/scriptlets/commit/7b3c3681bca4a37551b33837ddb85f187aa0236f
